version: 0.0
os: linux

files:
  - source: /
    destination: /src/pyspark-apps

file_exists_behavior: OVERWRITE

permissions:
  - object: /src/pyspark-apps
    owner: spark
    group: spark
    mode: 755

hooks:
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 120
      runas: spark